execute_process(
  COMMAND llvm-config --cxxflags
  OUTPUT_VARIABLE LLVM_DEFINITIONS)

execute_process(
  COMMAND llvm-config --includedir
  OUTPUT_VARIABLE LLVM_INCLUDE_DIR
  OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(
  COMMAND llvm-config --libdir
  OUTPUT_VARIABLE LLVM_LIB_DIR
  OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(
  COMMAND llvm-config --version
  OUTPUT_VARIABLE LLVM_VERSION
  OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(
  COMMAND llvm-config --system-libs
  OUTPUT_VARIABLE LLVM_SYSTEM_LIBS
  OUTPUT_STRIP_TRAILING_WHITESPACE)

find_library(LLVM_LIBRARY NAMES LLVM-${LLVM_VERSION} PATHS ${LLVM_LIB_DIR})
mark_as_advanced(LLVM_LIBRARY)

set(LLVM_LIBRARIES ${LLVM_LIBRARY} ${LLVM_SYSTEM_LIBS})
set(LLVM_INCLUDE_DIRS ${LLVM_INCLUDE_DIR})
set(LLVM_DEFINITIONS ${LLVM_DEFINITIONS} "-fno-rtti")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LLVM DEFAULT_MSG LLVM_LIBRARIES LLVM_INCLUDE_DIRS)
